In [2]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
data = pd.read_csv('../input/knn-dataset/weight-height.csv')

In [4]:
data

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
8550  Female  60.483946  110.565497
8551  Female  63.423372  129.921671
8552  Female  65.584057  155.942671
8553  Female  67.429971  151.678405
8554  Female  60.921791  131.253738

[8555 rows x 3 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8555 entries, 0 to 8554
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  8555 non-null   object 
 1   Height  8555 non-null   float64
 2   Weight  8555 non-null   float64
dtypes: float64(2), object(1)
memory usage: 200.6+ KB


In [6]:
data.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [7]:
# from sklearn.preprocessing import LabelEncoder
# lb1 = LabelEncoder()
# dataset = data['Gender'] = lb1.fit_transform(y)
# x = dataset
# x

from pandas.core.dtypes.common import is_numeric_dtype
from sklearn.preprocessing import LabelEncoder
lb1 = LabelEncoder()
for col in data.columns:
    if is_numeric_dtype(data[col]):
        continue
    else:
        data[col] = lb1.fit_transform(data[col])
        
print(data.head())

   Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801


In [8]:
x= data.drop("Weight",axis=1)
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [9]:
y = data[["Weight"]]

y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = .30, random_state = 1)

In [11]:
#check all shape here 
print('Shape of X_train = ', x_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', x_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5988, 2)
Shape of y_train =  (5988, 1)
Shape of X_test =  (2567, 2)
Shape of y_test =  (2567, 1)


In [12]:
x_train.head()

Gender     Height
1277       1  72.385301
5361       0  60.960147
5728       0  69.119292
4276       1  68.271050
3112       1  64.991405

In [13]:
y_train.head()

Weight
1277  189.165592
5361  124.876796
5728  168.864403
4276  172.941248
3112  144.551044

In [14]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm

LinearRegression()

In [15]:
lm.fit(x_train, y_train)
prediction = lm.predict(x_test)
print(prediction)

[[143.83013436]
 [197.53417989]
 [184.63515112]
 ...
 [160.7078525 ]
 [186.82852694]
 [201.4226542 ]]


In [16]:
lm.coef_

array([[19.34359322,  5.96887438]])

In [17]:
lm.intercept_

array([-244.55280903])

In [18]:
predcition = lm.predict(x_test)
prediction

array([[143.83013436],
       [197.53417989],
       [184.63515112],
       ...,
       [160.7078525 ],
       [186.82852694],
       [201.4226542 ]])

In [19]:
lm.predict([[1,71.476101]])

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([[201.42265253]])

In [20]:
lr_score=lm.score(x_train,y_train)
lr_score

0.8972135459668117

In [21]:
lr_score=lm.score(x_test,y_test)
lr_score

0.905995960709116

In [22]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
mean_squared_error(y_test,predcition)

99.67250998070033

In [23]:
mean_absolute_error(y_test, predcition)

7.98213259272913

In [24]:
from sklearn.neighbors import KNeighborsRegressor
KNN = KNeighborsRegressor(weights= 'uniform')
KNN

KNeighborsRegressor()

In [25]:
KNN.fit(x_train,y_train)
predcition_2 = KNN.predict(x_test)
predcition_2

array([[150.1761117 ],
       [197.46276978],
       [179.03501546],
       ...,
       [160.26227546],
       [180.65461322],
       [200.56451578]])

In [26]:
mean_squared_error(y_test,predcition_2)

123.15365863436983

In [27]:
mean_absolute_error(y_test,predcition_2)

8.850747809837165

In [28]:
kNN_score = KNN.score(x_test,y_test)
kNN_score

0.8838502073708883

In [29]:
x_test.iloc[-1, :]

Gender     1.000000
Height    71.476101
Name: 233, dtype: float64

In [30]:
y_test.iloc[-1]

Weight    195.392618
Name: 233, dtype: float64

In [31]:
y_test.shape

(2567, 1)

In [32]:
KNN.predict([x_test.iloc[-1, :]])

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([[200.56451578]])